# Generated by Django 6.0.6 on 2026-07-03 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NOSHOW', 'No Show')], db_index=True, default='PENDING', max_length=15)),
                ('reason_for_visit', models.TextField(help_text='Chief complaint o dahilan ng pagpunta ng pasyente.')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Sulat dito kung bakit kinansela ang appointment.', null=True)),
                ('token_number', models.PositiveIntegerField(blank=True, help_text='Queue number ng pasyente sa araw na iyon.', null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
