# Generated by Django 6.0.6 on 2026-07-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_doctorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
