# Generated by Django 6.0.6 on 2026-07-03 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('allergen', models.CharField(db_index=True, max_length=100)),
                ('reaction', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Moderate'), ('HIGH', 'Severe / Life Threatening')], default='LOW', max_length=10)),
            ],
            options={
                'verbose_name': 'Patient Allergy',
                'verbose_name_plural': 'Patient Allergies',
                'db_table': 'patient_allergies',
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('condition_name', models.CharField(db_index=True, max_length=150)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('treatment_received', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patient Medical History',
                'db_table': 'patient_medical_histories',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_notes', models.TextField(blank=True, help_text='Allergies or chronic conditions', null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, default='Filipino', max_length=50, null=True)),
                ('land_line', models.CharField(blank=True, max_length=20, null=True)),
                ('address_info', models.CharField(blank=True, max_length=255, null=True)),
                ('brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('phil_health', models.CharField(blank=True, max_length=20, null=True)),
                ('senior_id', models.CharField(blank=True, max_length=20, null=True)),
                ('hmo_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('hmo_accnum', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'patient_profiles',
            },
        ),
    ]
