# Generated by Django 6.0.6 on 2026-06-30 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('allergen', models.CharField(db_index=True, help_text='e.g., Penicillin, Peanuts, Latex', max_length=100)),
                ('reaction', models.TextField(help_text='Ano ang nangyayari? e.g., Rashes, Anaphylaxis')),
                ('severity', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Moderate'), ('HIGH', 'Severe / Life Threatening')], default='LOW', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Allergy',
                'verbose_name_plural': 'Patient Allergies',
                'db_table': 'patient_allergies',
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('condition_name', models.CharField(db_index=True, help_text='e.g., Hypertension, Diabetes', max_length=150)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('treatment_received', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Medical History',
                'db_table': 'patient_medical_histories',
            },
        ),
    ]
