# Generated by Django 6.0.6 on 2026-07-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(help_text='Halimbawa: Pediatrician, Cardiologist', max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('clinic_room', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField(help_text='Format: HH:MM:SS (e.g., 09:00:00)')),
                ('end_time', models.TimeField(help_text='Format: HH:MM:SS (e.g., 17:00:00)')),
                ('max_patients', models.PositiveIntegerField(default=10)),
            ],
            options={
                'db_table': 'doctor_schedules',
            },
        ),
    ]
