# Generated by Django 6.0.6 on 2026-06-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorschedule',
            table='doctor_schedules',
        ),
    ]
