# Generated by Django 6.0.6 on 2026-06-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorschedule_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorprofile',
            table='doctor_profiles',
        ),
    ]
